# Discord bot token
Token:

# Bot prefix
Prefix:

# Maximum alerts per user
Max-Alerts:

# Bot status displayed on Discord
Watching Status:

# Database host
DB-Host:

# Database user
DB-User:

# Database password
DB-Password:

# Database name
DB-Name:

# Database port
DB-Port:
